export const SEARCH_IMAGES = 'giphy/SEARCH_IMAGES'
export const SEARCH_IMAGES_SUCCESS = 'giphy/SEARCH_IMAGES_SUCCESS'
export const SEARCH_IMAGES_FAIL = 'giphy/SEARCH_IMAGES_FAIL'
export const CLEAR_SEARCH_IMAGES = 'giphy/CLEAR_SEARCH_IMAGES'
